### ISSUE TITLE
Failing builds

### ISSUE THREAD

**Issue by bowbahdoe** [immutables/immutables-vavr#17]
It seems like all the builds for this repo have been failing since November. Is this something to be concerned about?

**Comment by elucash** [comment]
For some reason, the release of _Immutables_ used in the build is no longer available. I can try to update to the newer alpha of 2.6.0 if that would be ok, @io7m ?

**Comment by elucash** [comment]
@bowbahdoe thank you for pointing this out! the build has been fixed, but I hope you can you released/available artifacts regardless of the build

**Comment by io7m** [comment]
Apologies, completely missed this one!

I have a private Jenkins setup here now, so I should learn about build failures much more quickly than on Travis CI.
