### ISSUE TITLE
inhibit-classpath is too aggressive

### ISSUE THREAD

**Issue by kennymacleod** [immutables/immutables-vavr#21]
vavr-encodings has a "classpath fence" configured for Immutables in the `META-INF/extensions/org.immutables.inhibit-classpath` file. This prevents the Immutables code generator from using any annotations in that package. 

I note from the commit comment that this has something to do with Java9 (likely to do with the split package problem in Jigsaw), but this seems like a pretty blunt instrument, and possibly not even necessary (with the current 2.6.x releases of Immutables, anyway - if the attempt to load the annotation class fails, it silently moves on). 

Can this inhibitor be removed? If people need to use this for their environment, then they can add the inhibitor themselves. Forcing it on everyone else just to accommodate Java9 seems wrong.

**Comment by elucash** [comment]
agree that this is something that should not be imposed automatically for all users, most probably this should not be needed if used with Immutables 2.6.x

**Comment by kennymacleod** [comment]
It doesn't really seem to have anything to do with vavr, either, it looks more like a general Java9 compatibility thing that should be dealt with as a separate concern elsewhere.

**Comment by kennymacleod** [comment]
It looks like this file is necessary when running the project build (since that requires the use of Java9+), so I've moved it from the `vavr-encodings` module to the `vavr-examples` module - see PR.

**Comment by io7m** [comment]
Closing this, as it will be fixed via #22 in the next release version.
