### ISSUE TITLE
Option type fields allow nulls

### ISSUE THREAD

**Issue by MFAshby** [immutables/immutables-vavr#27]
Expected behaviour:
A field typed with `Option` will throw a NullPointerException if you attempt to set `null` on an immutable object's field using the appropriate `.withSomeValue(null)` method. 

Actual behaviour:
The field will be set with `Some(null)` and no exception will be thrown.

I'm not actually 100% sure this is a bug but it's inconsistent with the behaviour for java.lang.Optional fields: those will throw an exception if you try to set a null. It's also in my opinion less safe: `Some(null)` is highly unexpected. 

The vavr library itself supports `Some(null)` deliberately, which has had some [significant previous discussion](https://github.com/vavr-io/vavr/issues/2392#issuecomment-475939435). I'm not sure if this applies to this library though.

I'll write a minimal reproduction of the issue if it helps.

**Comment by io7m** [comment]
Definitely a bug. I think part of the problem is that I didn't realize `vavr`'s `Option` type would accept null values.

**Comment by MFAshby** [comment]
I have a patch for it if it helps, it's relatively straightforward to add a few checks for not null.

**Comment by MFAshby** [comment]
Just found the same bug if the member is annotated with `@Value.Parameter`, there's no null check in the constructor. So: 

```java
@Value.Immutable
@VavrEncodingEnabled
public interface SomeObj {
    @Value.Parameter
    String someString();

    @Value.Parameter
    Option<String> someOptionString();
}

SomeObj o = ImmutableSomeObj.of("hello", null);
// Should throw a NullPointerException, but doesn't
```

Not totally sure where to fix this, looking now.

**Comment by MFAshby** [comment]
Found it, needs an `@Encoding.Of` adding.

**Comment by elucash** [comment]
yep, by default it's just passing the parameter to a field, if any check or conversion need to be added - `@Encoding.Of` is the way

**Comment by MFAshby** [comment]
PR coming up. Sorry I saw too slow to get this into v0.6.1!

**Comment by MFAshby** [comment]
I think this is fixed. Thanks so much for the quick response!
