### ISSUE TITLE
Rename project to immutables-vavr?

### ISSUE THREAD

**Issue by io7m** [immutables/immutables-vavr#5]
http://blog.vavr.io/javaslang-changes-name-to-vavr/

**Comment by io7m** [comment]
Will probably wait until they release their first `vavr` artifact on Central.

**Comment by io7m** [comment]
They've released `vavr 0.9.0` today, but the API is not yet stable so I'm going to delay this until they reach `1.0.0` (assuming that they do in a reasonable amount of time).

**Comment by emmanueltouzery** [comment]
Oh nice. That said i'm under the impression 1.0 will take months. That's just an impression though. I do think 0.9.0 would be worth supporting.

**Comment by io7m** [comment]
It might, yes. I likely won't leave it that long as I use these encodings myself.

**Comment by talios** [comment]
26 days ago last comment...  I'm moving projects over to vavr now, would be nice to see Immutables support it...

**Comment by emmanueltouzery** [comment]
We've implemented the support in our app, it's very little work. But I implemented it only for Option.

**Comment by io7m** [comment]
I'll try to get to this within the next few days. I'm working on some software right now that uses these, so now would be a good opportunity to make the switch.

**Comment by io7m** [comment]
I've pushed `vavr-encodings 0.4.0-SNAPSHOT` to Central. Please test this snapshot and report any problems in new tickets!
