### ISSUE TITLE
Upload the releases to maven central

### ISSUE THREAD

**Issue by zsolt-donca** [immutables/immutables-vavr#7]
It would be great if the artifacts of `immutables-vavr` would be uploaded to maven central, as somebody looking for this project could then easily use it in his or her project, without having to build the project locally and then upload it to some local artifact repository.

I've found that some early releases were uploaded to some [datastax repository](https://repo.datastax.com/public-repos/org/immutables/vavr/vavr-encodings/), but none of the new releases can be found there.

**Comment by io7m** [comment]
Hello!

The `immutables-vavr` project was renamed from `immutables-javaslang` a couple of weeks ago:

http://search.maven.org/#artifactdetails%7Corg.immutables.javaslang%7Cjavaslang-encodings%7C0.3.0%7Cjar

I pushed `0.4.0-SNAPSHOT` to the Sonatype snapshots repos at the time. Unless anyone has any new issues to file, I think it's probably time to release `0.4.0` and push it to Central under the new name.

**Comment by io7m** [comment]
`0.4.0` is up. It should be resolvable from Central now, but it'll be an hour or so before it appears in search listings.
