### ISSUE TITLE
Jackson encoding is broken

### ISSUE THREAD

**Issue by zsolt-donca** [immutables/immutables-vavr#8]
There is an issue when using immutables-vavr and [vavr's jackson encoding](https://github.com/vavr-io/vavr-jackson). For example:

```
@Value.Immutable
@VavrEncodingEnabled
@JsonSerialize
@JsonDeserialize
public interface Foo {
    Option<String> bar();
}
```

Produces the compilation error:
```
Error:java: Could not generate constructor. Attribute 'bar' does not have default value.
```

If I specify a default value, the error disappears, but I lose the special treatment that vavr encoding gives me in the builder. This seems to be an incompatbility between the two modules.

This issue is related to [this one](https://github.com/immutables/immutables/issues/614), where their workaround is to define a custom encoding for vavr types, replacing whatever `immutables-vavr` brings to the table.

**Comment by io7m** [comment]
This may be corrected in the `0.4.0-SNAPSHOT` I just pushed.

**Comment by zsolt-donca** [comment]
It indeed seems to be fixed for `Option`! But, it is not limited to `Option`s: `List`, `Map`, `Set`, and probably others, also seem to be affected.

**Comment by io7m** [comment]
Is it the same errors for the `List`, `Map`, etc, types?

```Error:java: Could not generate constructor. Attribute 'bar' does not have default value.```

I have to admit that I don't fully understand the underlying issue. If all that's needed to fix it is adding `@Encoding.Copy` methods, then I can easily get that done.

**Comment by zsolt-donca** [comment]
Yes, it is the same error. With the latest version from branch `develop`:
```
@Value.Immutable
@VavrEncodingEnabled
@JsonSerialize
@JsonDeserialize
public interface Foo {
    Option<String> option();
    List<String> list();
    Set<String> set();
    Map<String, Integer> map();
}
```
Results in the compiler errors:
```
Error:java: Could not generate constructor. Attribute 'list' does not have default value.
Error:java: Could not generate constructor. Attribute 'set' does not have default value.
Error:java: Could not generate constructor. Attribute 'map' does not have default value.
```

Option is fixed now, and JSON encoding/decoding also works.

**Comment by io7m** [comment]
Ah, so presumably it's just a matter of providing a default value for the `@Encoding.Impl` field. I'll update all of the types now.

**Comment by io7m** [comment]
Have a go with the snapshot I just pushed (`20170702.120216`).

**Comment by zsolt-donca** [comment]
I can confirm that your latest commits fix my use cases above. Nice job, especially considering that I've reported the bug just an hour ago! Thanks!

**Comment by io7m** [comment]
I'll likely push a release today if @emmanueltouzery confirms the snapshot as working.

**Comment by emmanueltouzery** [comment]
hmm i won't manage to test it today. tomorrow best case. i'd say go for it. i think in the case of our setup, we'll probably stick with a small-scale local implementation which supports only option, which is enough for us, we probably won't migrate to using this library.

**Comment by io7m** [comment]
Got it!

**Comment by zsolt-donca** [comment]
Great! :+1: 

Just one thing: I've noticed that you've introduced empty `HashSet` and `HashMap` as default values for `Set` and `Map`. Usually, I prefer to use the `Linked` versions of these classes, as they have a useful ordering semantics: converting JSON to some object and back again leads to the same JSON. This makes it easier to write tests, and also to compare for differences in case something fails (which is difficult if the ordering of elements is arbitrary).

What do you think? Does it make sense to you to use `LinkedHash[Set/Map]` as defaults? 

To me, it's not a serious issue what the defaults are, as I can always just directly use the type `LinkedHash[Set/Map]` in my immutable data types, though I'd prefer not to, as `LinkedHash` adds 10 more characters. :(

**Comment by io7m** [comment]
Seems like a low-cost change to improve serialization. I'll add it now.
